index:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }
    
login:
    path:     /login
    defaults: { _controller: FrontBundle:Default:login }

categorie:
    path:     /categorie/{id}
    defaults: { _controller: FrontBundle:Default:categorie }

deposerAnnonce:
    path:     /deposerAnnonce
    defaults: { _controller: FrontBundle:Default:deposerAnnonce }
view:
    path:     /annonce/{id}
    defaults: { _controller: FrontBundle:Annonce:view }

