index:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

deposerAnnonce:
    path:     /deposerAnnonce
    defaults: { _controller: FrontBundle:Depot:deposerAnnonce }
    
confirmer:
    path:     /confirmerAnnonce
    defaults: { _controller: FrontBundle:Form:inscription }    

categorie:
    path:     /categorie/{id}/{page}
    defaults: { _controller: FrontBundle:Annonce:categorie, page: 1 }
    
view:
    path:     /annonce/{id}
    defaults: { _controller: FrontBundle:Annonce:view }

search:
    path:     /search
    defaults: { _controller: FrontBundle:Recherche:search }
    
connexion:
    path:     /connexion
    defaults: { _controller: FrontBundle:Utilisateur:connexion }   

inscription:
    path:     /inscription
    defaults: { _controller: FrontBundle:Utilisateur:inscription }
    
gestion_categorie:
    path:     /gestionCat
    defaults: { _controller: FrontBundle:Admin:categorie }    