index:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

deposerAnnonce:
    path:     /deposerAnnonce
    defaults: { _controller: FrontBundle:Depot:deposerAnnonce }

categorie:
    path:     /categorie/{id}/{page}
    defaults: { _controller: FrontBundle:Annonce:categorie, page: 1 }
    
view:
    path:     /annonce/{id}
    defaults: { _controller: FrontBundle:Annonce:view }

search:
    path:     /search
    defaults: { _controller: FrontBundle:Recherche:search }
    
login:
    path:     /login
    defaults: { _controller: FrontBundle:Utilisateur:login }

inscription:
    path:     /inscription
    defaults: { _controller: FrontBundle:Utilisateur:inscription }